### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gianghl1983** [codeboxrcodehub/cbxphpspreadsheet#2]
Hi,

After install the plugin, do I have to download PHPSpreadsheet manually and upload to my WordPress site?

I can use the plugin now, but I wonder how I can modify plugin so that I can host my own PHP Spreadsheet library somewhere in my Git and point the plugin to that?_

Br,

**Comment by manchumahara** [comment]
@gianghl1983 pls check the readme file https://github.com/codeboxrcodehub/cbxphpspreadsheet/blob/master/README.txt  and read documentation is in https://phpspreadsheet.readthedocs.io/
