### ISSUE TITLE
Please Support PHP version >=7.4

### ISSUE THREAD

**Issue by vfic** [codeboxrcodehub/cbxphpspreadsheet#3]
I cann't export data to XLSX file when I update PHP version to 7.4 or above

**Comment by lstamatis** [comment]
I have also the same issue, did you find any solution?

**Comment by manchumahara** [comment]
I updated this plugin with latest https://phpspreadsheet.readthedocs.io/en/latest/  can you please check now

**Comment by vfic** [comment]
> I updated this plugin with latest https://phpspreadsheet.readthedocs.io/en/latest/ can you please check now

Thank you.
