### ISSUE TITLE
Doesn't work export data to xlsx file on PHP version  >= 7.4

### ISSUE THREAD

**Issue by lstamatis** [codeboxrcodehub/cbxphpspreadsheet#4]

**Comment by manchumahara** [comment]
need to check, I think we didn't update the actual library for long. the main php spreadsheet library is here  if you need to implement as your own https://github.com/PHPOffice/PhpSpreadsheet

**Comment by manchumahara** [comment]
https://phpspreadsheet.readthedocs.io/en/latest/
